### ISSUE TITLE
error run

### ISSUE THREAD

**Issue by NickyDark1** [fe1ixxu/CPO_SIMPO#2]
## img
![image](https://github.com/fe1ixxu/CPO_SIMPO/assets/123802672/20bc7aaf-f7bb-43d2-89c0-2a6ab2b279fe)

## code
```
!pip install deepspeed
!pip uninstall numpy -y
!pip install "numpy<2.0.0"
!pip install alignment
```
## code version
```
import numpy
numpy.__version__
# '1.26.4'
```
```
!ACCELERATE_LOG_LEVEL=info accelerate launch --config_file CPO_SIMPO/accelerate_configs/deepspeed_zero3.yaml CPO_SIMPO/scripts/run_cpo.py CPO_SIMPO/training_configs/llama-3-8b-instruct-cpo-simpo.yaml
```

## error
```
[2024-06-21 04:58:16,039] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
INFO:root:Using nproc_per_node=8.
W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] 
W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] *****************************************
W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] *****************************************
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
Traceback (most recent call last):
  File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
    from alignment import (
ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21005 closing signal SIGTERM
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21006 closing signal SIGTERM
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21007 closing signal SIGTERM
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21008 closing signal SIGTERM
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21010 closing signal SIGTERM
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21011 closing signal SIGTERM
W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21012 closing signal SIGTERM
E0621 04:58:19.414000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 4 (pid: 21009) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1082, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 786, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
CPO_SIMPO/scripts/run_cpo.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-21_04:58:19
  host      : 352b61709965
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 21009)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by sahsaeedi** [comment]
> ## img
> ![image](https://private-user-images.githubusercontent.com/123802672/341642394-20bc7aaf-f7bb-43d2-89c0-2a6ab2b279fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MDk0MDksIm5iZiI6MTcyMjcwOTEwOSwicGF0aCI6Ii8xMjM4MDI2NzIvMzQxNjQyMzk0LTIwYmM3YWFmLWY3YmItNDNkMi04OWMwLTJhNmFiMmIyNzlmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxODE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDY4MWE5ZmRmNGQzOTcxZTZjNzI3ZTZkZWNkNjMzNzM3NTE3YzBjMWVhZTBjOTY0NjFkNjAxNWJlMjYzZGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Qdu5cpAoTiOm17htksfx3jLOA7TSBcYJ9fLPl7a72Y)
> 
> ## code
> ```
> !pip install deepspeed
> !pip uninstall numpy -y
> !pip install "numpy<2.0.0"
> !pip install alignment
> ```
> 
> ## code version
> ```
> import numpy
> numpy.__version__
> # '1.26.4'
> ```
> 
> ```
> !ACCELERATE_LOG_LEVEL=info accelerate launch --config_file CPO_SIMPO/accelerate_configs/deepspeed_zero3.yaml CPO_SIMPO/scripts/run_cpo.py CPO_SIMPO/training_configs/llama-3-8b-instruct-cpo-simpo.yaml
> ```
> 
> ## error
> ```
> [2024-06-21 04:58:16,039] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
>  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
>  [WARNING]  async_io: please install the libaio-dev package with apt
>  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
>  [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
>  [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
>  [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
> INFO:root:Using nproc_per_node=8.
> W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] 
> W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] *****************************************
> W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> W0621 04:58:17.125000 135994699546624 torch/distributed/run.py:757] *****************************************
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> Traceback (most recent call last):
>   File "/workspace/CPO_SIMPO/scripts/run_cpo.py", line 24, in <module>
>     from alignment import (
> ImportError: cannot import name 'DataArguments' from 'alignment' (/usr/local/lib/python3.10/dist-packages/alignment/__init__.py)
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21005 closing signal SIGTERM
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21006 closing signal SIGTERM
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21007 closing signal SIGTERM
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21008 closing signal SIGTERM
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21010 closing signal SIGTERM
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21011 closing signal SIGTERM
> W0621 04:58:19.350000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 21012 closing signal SIGTERM
> E0621 04:58:19.414000 135994699546624 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 4 (pid: 21009) of binary: /usr/bin/python
> Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
>     args.func(args)
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1082, in launch_command
>     deepspeed_launcher(args)
>   File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 786, in deepspeed_launcher
>     distrib_run.run(args)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 870, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> CPO_SIMPO/scripts/run_cpo.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-06-21_04:58:19
>   host      : 352b61709965
>   rank      : 4 (local_rank: 4)
>   exitcode  : 1 (pid: 21009)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

Check the alignment handbook repo (https://github.com/huggingface/alignment-handbook), and instead of installing it, use their functions directly.
